const paragraphs = ['Habitant morbi tristique senectus et netus et malesuada fames. Consequat id porta nibh venenatis cras sed felis. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Scelerisque purus semper eget duis at tellus. Gravida rutrum quisque non tellus orci ac auctor augue mauris. Vivamus at augue eget arcu. Lectus magna fringilla urna porttitor rhoncus dolor purus non. Vel pharetra vel turpis nunc eget. Enim nunc faucibus a pellentesque sit. Interdum varius sit amet mattis vulputate enim nulla aliquet. Nunc non blandit massa enim nec dui nunc mattis enim. Dictum fusce ut placerat orci nulla pellentesque. Erat velit scelerisque in dictum non consectetur a. Enim diam vulputate ut pharetra sit amet aliquam id. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Turpis nunc eget lorem dolor sed.',
  'Proin libero nunc consequat interdum varius sit. A cras semper auctor neque vitae tempus quam pellentesque nec. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Neque volutpat ac tincidunt vitae semper quis lectus. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Aliquet eget sit amet tellus cras adipiscing. Aliquam malesuada bibendum arcu vitae. Sed cras ornare arcu dui vivamus arcu felis bibendum. Ultricies leo integer malesuada nunc. Pharetra vel turpis nunc eget lorem dolor. Ultrices in iaculis nunc sed augue lacus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Consectetur a erat nam at lectus urna. Odio aenean sed adipiscing diam donec adipiscing. Enim facilisis gravida neque convallis a. Vulputate ut pharetra sit amet. Tellus molestie nunc non blandit massa enim nec. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Sed viverra ipsum nunc aliquet bibendum enim. In est ante in nibh mauris cursus.',
  'Amet nisl purus in mollis nunc sed id.Lorem mollis aliquam ut porttitor.Egestas tellus rutrum tellus pellentesque eu tincidunt tortor.Commodo nulla facilisi nullam vehicula ipsum.Turpis tincidunt id aliquet risus feugiat in.Neque vitae tempus quam pellentesque nec.Sed libero enim sed faucibus turpis in.Ultricies mi eget mauris pharetra et ultrices neque ornare aenean.Senectus et netus et malesuada.Metus vulputate eu scelerisque felis.Aliquam sem fringilla ut morbi tincidunt augue interdum.Semper eget duis at tellus at urna condimentum mattis.',
  'Nam at lectus urna duis convallis convallis.Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat.Pharetra et ultrices neque ornare aenean euismod elementum nisi.Ipsum dolor sit amet consectetur adipiscing elit.Arcu ac tortor dignissim convallis aenean et tortor.Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat.Tellus mauris a diam maecenas sed enim.Nunc mattis enim ut tellus elementum sagittis vitae et leo.Tempus urna et pharetra pharetra massa.Ac tortor vitae purus faucibus ornare suspendisse sed nisi.Enim blandit volutpat maecenas volutpat blandit aliquam.Cursus sit amet dictum sit amet justo donec enim diam.',
  'Aliquam nulla facilisi cras fermentum odio eu feugiat pretium.Non curabitur gravida arcu ac tortor dignissim.Bibendum at varius vel pharetra vel turpis nunc.Quam vulputate dignissim suspendisse in est.Lorem ipsum dolor sit amet consectetur adipiscing elit.Tincidunt arcu non sodales neque sodales ut etiam sit.Vitae turpis massa sed elementum tempus egestas sed sed risus.Vel turpis nunc eget lorem.Dolor sed viverra ipsum nunc.Proin fermentum leo vel orci porta non pulvinar neque laoreet.Dui ut ornare lectus sit amet est placerat in egestas.Eget egestas purus viverra accumsan in nisl nisi.Sagittis purus sit amet volutpat consequat mauris nunc congue.Eu scelerisque felis imperdiet proin.In hendrerit gravida rutrum quisque non tellus orci.Enim sed faucibus turpis in eu mi bibendum neque egestas.',
  'Eu volutpat odio facilisis mauris sit.Id donec ultrices tincidunt arcu non sodales neque sodales ut.Sit amet porttitor eget dolor morbi.Scelerisque eu ultrices vitae auctor.Dignissim suspendisse in est ante in nibh mauris.Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus.Sed velit dignissim sodales ut eu sem integer.Erat imperdiet sed euismod nisi.Non curabitur gravida arcu ac tortor.Nunc sed id semper risus in hendrerit.Sit amet facilisis magna etiam tempor orci eu lobortis.Augue neque gravida in fermentum et.Sed id semper risus in hendrerit gravida rutrum quisque.',
  'Vel orci porta non pulvinar neque laoreet.Vitae nunc sed velit dignissim sodales ut.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim.Amet dictum sit amet justo.Semper feugiat nibh sed pulvinar proin.Justo eget magna fermentum iaculis eu non diam.In fermentum et sollicitudin ac orci phasellus.Adipiscing commodo elit at imperdiet dui accumsan sit.Tortor consequat id porta nibh venenatis.Luctus venenatis lectus magna fringilla urna porttitor rhoncus.Pellentesque elit eget gravida cum sociis.Sapien faucibus et molestie ac feugiat.Lacinia quis vel eros donec ac odio tempor orci dapibus.Faucibus a pellentesque sit amet.Quam adipiscing vitae proin sagittis.',
  'Ullamcorper morbi tincidunt ornare massa eget.Pellentesque sit amet porttitor eget dolor morbi non arcu risus.Cras pulvinar mattis nunc sed blandit libero volutpat sed.Dictumst quisque sagittis purus sit amet volutpat.Nullam vehicula ipsum a arcu.Ultrices dui sapien eget mi proin sed libero enim.Feugiat in fermentum posuere urna nec tincidunt praesent.Congue quisque egestas diam in arcu cursus.Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper.Sed turpis tincidunt id aliquet risus feugiat in ante.Bibendum at varius vel pharetra vel.',
  'Enim lobortis scelerisque fermentum dui faucibus in ornare.Sem nulla pharetra diam sit amet nisl suscipit.Malesuada nunc vel risus commodo viverra.Nec ullamcorper sit amet risus.Senectus et netus et malesuada fames ac.Tempus quam pellentesque nec nam aliquam.Viverra mauris in aliquam sem fringilla.Dictum non consectetur a erat nam at lectus urna.Arcu non sodales neque sodales ut etiam sit amet.Sit amet massa vitae tortor condimentum lacinia quis vel eros.Facilisis magna etiam tempor orci.Purus faucibus ornare suspendisse sed nisi lacus sed viverra.Ullamcorper a lacus vestibulum sed arcu.'];

const button = document.querySelector('#add-another-paragraph');
const paragraphWrapper = document.querySelector('#paragraph-wrapper');

button.addEventListener('click', () => {
  const paragraph = document.createElement('p');

  paragraph.textContent = paragraphs[Math.floor(Math.random() * paragraphs.length)];

  paragraphWrapper.appendChild(paragraph);
});